version: "3.5"

services:
  # api-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   entrypoint: ./api-server
  #   restart: always

  db:
    image: postgres:14.1-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gogolook
